baseURL: "https://example.com"
theme: "hugo-theme-novela"
languageCode: "en-us"
title: "NeuronHub"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  facebook: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
